name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  release-test:
    name: Test for Release
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, 1.63.0]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt
      - name: Run format checking
        run: cargo fmt -- --check
      - name: Run cargo test (with OpenSSL cipher backend)
        run: cargo test --release
      - name: Run cargo test (with RustCrypto cipher backend)
        run: cargo test --release --no-default-features --features=rustcrypto-cipher

  release:
    name: Release & Publish to crates.io
    runs-on: ubuntu-latest
    needs: release-test
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Cargo Login
        run: cargo login -- ${{ secrets.CARGO_TOKEN }}
      - name: Cargo Publish
        run: cargo publish
