name: Run Tests
on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, 1.63.0, nightly]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set git to use LF on Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      ## non-Windows
      - name: Run cargo test (with OpenSSL cipher backend)
        if: ${{ runner.os != 'Windows' }}
        run: cargo test
      - name: Run cargo test (with RustCrypto cipher backend)
        if: ${{ runner.os != 'Windows' }}
        run: cargo test --no-default-features --features=rustcrypto-cipher
      ## Windows
      - name: Run cargo test (with OpenSSL cipher backend)
        if: ${{ runner.os == 'Windows' }}
        run: cargo test --features=openssl-vendored
      - name: Run cargo test (with RustCrypto cipher backend)
        if: ${{ runner.os == 'Windows' }}
        run: cargo test --no-default-features --features=rustcrypto-cipher,openssl-vendored
